import { Anek_Telugu } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import Document from "@/document";
import Navbar from "./component/navbar";
import Footer from "./component/footer"
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
const inter = Anek_Telugu({ subsets: ["latin-ext"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </body>
      <Document></Document>

    </html>
  );
}
